### ISSUE TITLE
It does not work for PLUS account during progress quiz 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#11]
It does not work for PLUS account during progress quiz @
https://www.duolingo.com/progress-quiz/es

**Comment by derat** [comment]
I don't have a Plus account, unfortunately.

If the structure of the quiz seems similar to one of the other test/skill/practice/etc. types, then you could load an unpacked copy of the extension and try tweaking `onMutation()` in `content.js` to see if the existing logic will work. You should be able to change one of these conditions:

```js
    const isPractice = window.location.href.indexOf('/practice') != -1;
    const isSkill = window.location.href.indexOf('/skill/') != -1;
    const isSkillTest = isSkill && window.location.href.endsWith('/test');
    const isBigTest = window.location.href.indexOf('/bigtest/') != -1;
    const isCheckpoint = window.location.href.indexOf('/checkpoint/') != -1;
    const isStory = window.location.href.indexOf('/stories/') != -1;
```

For example, you could change the first line to:

```js
    const isPractice = window.location.href.indexOf('/practice') != -1 ||
                       window.location.href.indexOf('/progress-quiz/') != 1;
```

to make progress quiz URLs get the same treatment as practice URLs.

**Comment by alexseyk** [comment]
I don't have it anymore either. If / when i get another free week of plus of my friends i'll give it a try.

**Comment by alexseyk** [comment]
Hi there, So I got a week of plus and gave it a try. 
I made the changes as you suggested and it worked. 

Please add  the changes to next release.

**Comment by derat** [comment]
Thanks for testing it. I've uploaded 0.23 to the Chrome Web Store.
