### ISSUE TITLE
Does not work with Dark Reader - ON

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#12]
It stops working when Dark Reader is ON on Chrome  Version 80.0.3987.149 (Official Build) (64-bit) :( 
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

I tried with Dark Theme for Chrome & Dark theme suite extensions  too. It did not work either. Can you fix or recommend a dark mode that works with your extension ?
Thanks

**Comment by alexseyk** [comment]
It works!! with Dark Mode :)  https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj

**Comment by derat** [comment]
Glad to hear it!

And, yeah, in general there's probably not much that can be done if other extensions also inject content scripts that modify the page. I'm already worried about how fragile the extension is just by depending on the colors/layout/etc. of the stock Duolingo site.

**Comment by alexseyk** [comment]
On the bright side it still works after yesterdays web-site redesign:) some other extensions / scripts that i have stopped working
