### ISSUE TITLE
Skip Jump to Next Level page 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#13]
When using a "key" to jump to next level 
 
<img width="350" alt="Screen Shot 2020-05-16 at 12 27 00" src="https://user-images.githubusercontent.com/60418150/82111697-210fbe80-9771-11ea-8e28-19ce6a83abbf.png">

there is a page that can be skipped
<img width="950" alt="Screen Shot 2020-05-16 at 12 31 59" src="https://user-images.githubusercontent.com/60418150/82111715-4a304f00-9771-11ea-8e22-c8201c02a45c.png">
Please add it to skipped pages list .

**Comment by derat** [comment]
Thanks, I just uploaded 0.9 in the Chrome Web Store to skip these as well.

(The store made me submit a justification for the existing "storage" permission that's used to save your options, so it may take a while before the new version is published if it needs to be reviewed by a human.)

**Comment by alexseyk** [comment]
got it. thanks. it works :)
