### ISSUE TITLE
wrong auto progress :(

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#14]
In checkpoint challenge via tower  and in skill test out to next level via key. It is not possible  to type in the answer or use  the word bank  :( - an answer is marked wrong and page skipped to next. 
using v 0.9 on Chrome + DuoStrength & SolutionViewer extensions if it matters 
Uk - > En &  En - > Es courses 

same for v 0.10

**Comment by derat** [comment]
Do you mean that it's automatically clicking the next button before you can answer? Is this a new issue? Can you check if it still happens if you disable other Duolingo-related extensions?

**Comment by alexseyk** [comment]
It is an old issue. at least since one of the duo's recent changes.  It auto clicks  next button right after i type just one letter. :( 
The issue is still there with all extensions disabled. 
<img width="607" alt="Screen Shot 2020-05-28 at 10 14 18" src="https://user-images.githubusercontent.com/60418150/83094512-0708a100-a0cc-11ea-9214-5030224eec45.png">

**Comment by alexseyk** [comment]
and using word bank i can select only one tile before the next button is trigged

**Comment by alexseyk** [comment]
Hi
The issue seems to be unresolved for checkpoints i.e for this type of links  https://www.duolingo.com/checkpoint/en/0
I just tried with v 0.11

**Comment by derat** [comment]
I tried maybe ten /checkpoint URLs but haven't seen the problem. The first question I get always seems to be multiple choice, so there's no chance to type or use a word bank, and hence no chance for my answer to get interrupted.

If you want to try out a potential fix, I've checked in https://github.com/derat/duoleavemealone/commit/1a4e2e56eea088c5fd5b120c83509743fb3a54a8, though. I haven't pushed it to the web store, but you should be able to load the latest code as an unpacked extension.

**Comment by alexseyk** [comment]
Ok It fixes it ! Note that original issue was for checkpoints not bigtest. Type or word bank questions were not the first for me either, they appear later and then an error was triggered.  Using volunteer made (non CEFR)  courses (like Latin or Ukrainian )will give you a type (word bank) question sooner.
