### ISSUE TITLE
Blue "continue" button at the end of stories  - skip too. 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#20]
Can you also skip the blue "continue" button at the end of the stories. Thanks
<img width="474" alt="Screen Shot 2020-11-22 at 16 21 17" src="https://user-images.githubusercontent.com/60418150/99899846-d4d4a680-2cde-11eb-99ba-5876c967b032.png">
<img width="453" alt="Screen Shot 2020-11-22 at 16 21 30" src="https://user-images.githubusercontent.com/60418150/99899855-d900c400-2cde-11eb-8d61-dacd63c854bb.png">

**Comment by derat** [comment]
Thanks, this will be fixed in 0.19.
