### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by tech189** [derat/duoleavemealone#26]
This looks like a useful extension but I don't use Chrome unfortunately, would it be possible to port your extension to Firefox? I found a guide that may be useful and I didn't find any issues when I tested it in the compatibility tester but no worries if you're not up for it!
https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

**Comment by derat** [comment]
Sorry, I don't have time to maintain a second version of the extension in Mozilla's add-ons site right now. :-(

I also only saw one (harmless?) warning from the extensiontest.com:

```json
    {
      "message": "\"storage.sync\" can cause issues when loaded temporarily",
      "description": "This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications|browser_specific_settings > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.",
      "locations": [
        {
          "file": "options.js",
          "line": 20
        },
        {
          "file": "options.js",
          "line": 37
        },
        {
          "file": "content.js",
          "line": 7
        }
      ]
    }
```

If you haven't already tried it, it might be worth checking out the repository and trying to load it in Firefox via `about:debugging`. https://developer.mozilla.org/en-US/docs/Tools/about:debugging has instructions, I think (in the "Loading a temporary extension" section).

**Comment by SocietasEvanescentes** [comment]
> This looks like a useful extension but I don't use Chrome unfortunately, would it be possible to port your extension to Firefox? I found a guide that may be useful and I didn't find any issues when I tested it in the compatibility tester but no worries if you're not up for it! https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

Firefox version is in the process of being approved by Mozilla reviewers. 
<img width="557" alt="Screen Shot 2022-05-31 at 12 07 33 PM" src="https://user-images.githubusercontent.com/25782090/171219520-a9f05aa1-ccd5-4b53-95a0-3df40072e1e8.png">

**Comment by SocietasEvanescentes** [comment]
Now available on addons.mozilla.org: https://addons.mozilla.org/en-US/firefox/addon/duoleavemealone-for-duolingo/

**Comment by derat** [comment]
Thanks!
