### ISSUE TITLE
Skip timed practice 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#4]
Please add option to skip timed practice 
i.e. always click (Practice without a timer)  instead of  (Start timed practice) that Duo forces us to use

**Comment by derat** [comment]
Thanks for the great suggestions! I just published an updated version of the extension to the Chrome Web Store (0.7), but it looks like it may take a couple of days to go through review.

When you have the updated version, you should be able to change the options by right-clicking the extension icon in the toolbar. Let me know if you run into any problems! I had to enable the "storage" permission to save the setting, but hopefully the extension won't be automatically disabled until you accept the new permission.

**Comment by alexseyk** [comment]
FYI i received ver 0.7 ^)==:)
