### ISSUE TITLE
Enable your extension for the towers - checkpoint  & test-out skills  

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#5]
Enable your extension for the towers - **checkpoint**    & **test-out skills**  lesson / test / exercise. not sure how to call them

**Comment by alexseyk** [comment]
So it works for test-out but does NOT work for checkpoint challenge 
check on any of your trees, language not important 

https://www.duolingo.com/checkpoint/es/0

works for this one 
https://www.duolingo.com/bigtest/es/0

I admit, there not many pages to skip there :) just 1 in beginning and few at the end

**Comment by derat** [comment]
Whoops, didn't realize that there were different URLs. Should be fixed in 0.8, which I just published.

Just to mention it, I got a "how much did you know before you started using Duolingo?" survey at the beginning, which won't be skipped.

**Comment by alexseyk** [comment]
thanks. btw this message is not shown in all courses
