### ISSUE TITLE
motivational message after several mistakes not caught

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#6]
FYI:  motivational message that is shown after several mistakes is not caught
<img width="1403" alt="Screen Shot 2020-02-28 at 11 18 51" src="https://user-images.githubusercontent.com/60418150/75510155-9397ba80-5a1c-11ea-990f-c2501e50c948.png">

**Comment by derat** [comment]
Yeah, those are hard to detect. Were you in practice mode? I think it sometimes doesn't work there -- see https://github.com/derat/duoleavemealone/issues/1#issuecomment-578113729. Hard to figure out what's going on since I don't know of any way to reliably trigger the messages.

**Comment by alexseyk** [comment]
Yes I was in the non-timed practice mode for an individual skill. Ok I understand now that you need a way to trigger message to block it. I thought you can catch it by a message or id like "you can do" 

There are also tips that are shown when you make certain mistakes. They are somewhat useless once you see it once or twice. 
Blocking them may be controversial. Please consider  adding it in the options.

**Comment by derat** [comment]
Oh, I agree that those tips are useless. In Spanish, they sometimes even give incorrect advice. I'd be happy to skip them if I could, but I think that you need to answer them correctly to progress!

I initially had a hardcoded list of messages to skip, but I think that that approach would only work when the UI is in English, and I'm trying to make the extension work for all languages.

The logic for detecting motivational messages is in motivationShown() in content.js. It currently looks for a "Continue" button with a background-color style of 'rgb(88, 167, 0)' and a div element with a background-image URL containing the text '/owls/'. The next time that you see a message that isn't skipped, please feel free to use Chrome's dev tools' "Elements" tab to try to figure out what's going wrong. I triggered a message in untimed practice by answering five questions wrong in a row, but it was skipped as expected.

**Comment by alexseyk** [comment]
You don't have to give a **correct** answer to progress from the "Here's a tip" screens, but you do need to give an answer. So if you can code to auto answer on "Here's a tip" page and then if answered wronlgly ... auto click on continue "button" with red background. 

I think you are safe to hardcode to look for a "Here's a tip"  for now. Those tips do not show up in all the courses.

I see them in En>Es too and so far hoping for something more useful than advise about selecting correct gender 

I will look for any not skipped motivational messages. May be some images do not have '/owls/' in their URL.
I will send you those URL to hardcode or crack the logic behind them.

**Comment by alexseyk** [comment]
this one not caught 
https://d35aaqx5ub95lt.cloudfront.net/images/owls/happy.svg
<div class="_3bFAF _1ottH _27r1x _3xka6">Even when you're wrong, you're still learning!</div>

**Comment by derat** [comment]
Thanks, but that URL contains '/owls', so I'm still at a loss for why it wouldn't be detected by motivationShown().

**Comment by alexseyk** [comment]
I see now that it is the same URL that is blocked on other occasions
I had the same motivational message again. (but this time followed by a" here's a tip" page) As far as i can tell the background-color style  is the same also. 
I am attaching that page. May be it'll help. 
and i got that message again after 3 wrong answers in a row... 
[Archive.zip](https://github.com/derat/duoleavemealone/files/4281037/Archive.zip)

**Comment by alexseyk** [comment]
https://www.duolingo.com/settings/account >  > Motivational messages

**Comment by derat** [comment]
Great to hear. Thanks for the update!
