### ISSUE TITLE
extend functional to Stories 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#9]
Please kindly add an option for your extension to work on stories pages. thanks 
https://stories.duolingo.com/?referrer=web_tab

**Comment by derat** [comment]
Reopening since it's controlled by an option that's off by default. Should mostly work, though.

**Comment by alexseyk** [comment]
i tried it. Yes the last word is omitted :( May be add an extra second or two before next button is clicked, just for stories ? 
LTS project posts direct links to audio files. May be there is a way to get audio file length ? 
[\[LTS\] Learn Through Stories : Overview](https://forum.duolingo.com/comment/36647198)

On the 2nd thought it won't work since audio plays uninterrupted by next buttons 
example:
 https://stories-cdn.duolingo.com/audio/3e5575f7e935cbc2815b53b028939446c184b7e8.mp3

**Comment by derat** [comment]
This should be working reasonably well with ddc2af94087f99da35069bf4232d6ee9b80b9e94. It'll go out in 0.13.

**Comment by alexseyk** [comment]
at the end of normal lessons or practice session there is a splash message stating how much xp were earned. May be you should do the same after stories? for consistency ?
